### ISSUE TITLE
heroku部署后的问题

### ISSUE THREAD

**Issue by winkxx** [666wcy/new_bot#2]
不好意思，又是我的问题，打搅到您的话真不好意思。我部署后log出现以下问题，下面是截图和log文本，我希望您可以帮我看看，解决下问题
![a077c9060c4ea14a8612a8000f6921b](https://user-images.githubusercontent.com/68945988/116576382-17f80d00-a942-11eb-896c-a4b7e67d56da.png)
[baion-logs-1619709910757.txt](https://github.com/666wcy/new_bot/files/6399820/baion-logs-1619709910757.txt)

**Comment by 666wcy** [comment]
内部使用，不对外开放

**Comment by 666wcy** [comment]
域内人员请私聊我tg
